### ISSUE TITLE
Fails if there are no production/development dependencies

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/npm-updatedt#3]
## Summary

Running this tool (at [v0.1.0](https://github.com/ericcornelissen/npm-updatedt/blob/db336414c055b67a8d298f6ed311cc461d7bb265/package.json#L3)) on an npm project without either production or development dependencies (and provided, resp., `--dev-only` or `--prod-only` aren´t used) it will blow up and output an error like:

```
file:///path/to/npm-updatedt/main.js:46
  for (const [name, version] of Object.entries(dependencies)) {
                                       ^

TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at updateDependencies (file:////path/to/npm-updatedt/main.js:46:40)
    at file:////path/to/npm-updatedt/main.js:130:3
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

Node.js v18.12.1
```

This is because the current implementation assumes `dependencies` and `devDependencies` are always present.

The tool should not assume this and skip trying to update either if not present.

**Comment by ericcornelissen** [comment]
Fixed with a3a164d5338b08fc228888d063592205d67f0110
